build_linux:
  script:
    - cd app/static
    - git submodule init
    - git submodule update
    - cd ../..
    - cp config.py.example config.py
    - coverage run run_tests.py
lint:
  allow_failure: true
  script:
    - pylint -f parseable -rn models plugins